#!/usr/bin/perl
# public domain

use warnings;
use strict;
use IO::Socket::INET;
use Time::HiRes;

$|++;
my $host        = shift @ARGV;
my $filename    = shift @ARGV;
my $value_size  = shift @ARGV;


my $s = connect_to($host);
die $@ unless $s;

open(FH, '>>', $filename) or die $!;
missrate();
close(FH);

sub missrate {
    my $one = mc_info($s);
    my $max_mem = $one->{"limit_maxbytes"};
    my $missRate = $one->{"get_misses"} / ($one->{"get_hits"} + $one->{"get_misses"});
    # printf FH "%d, %.3f\n", $max_mem, $missRate;
    printf FH "%d, %.3f\n", $max_mem / $value_size, $missRate;
}

sub mc_info {
    my $s = shift;
    print $s "stats\r\n";
    my %stats = ();
    while (my $line = <$s>) {
        last if $line =~ m/^END/;
        if ($line =~ m/^STAT (\S+) (\d+)/) {
            $stats{$1} = $2;
        }
    }
    return \%stats;
}


sub connect_to {
    return IO::Socket::INET->new(PeerAddr => $_[0], Timeout => 10);
}
